//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFArch.UI.BusinessLayer.OrderServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOrderByCustomerReguest", Namespace="http://schemas.datacontract.org/2004/07/WPFArch.WCF.DtoLibrary.Request.Order")]
    [System.SerializableAttribute()]
    public partial class GetOrderByCustomerReguest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOrderByCustomerResponse", Namespace="http://schemas.datacontract.org/2004/07/WPFArch.WCF.DtoLibrary.Response.Order")]
    [System.SerializableAttribute()]
    public partial class GetOrderByCustomerResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WPFArch.UI.BusinessLayer.OrderServiceReference.OrderDto> OrdersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WPFArch.UI.BusinessLayer.OrderServiceReference.OrderDto> Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDto", Namespace="http://schemas.datacontract.org/2004/07/WPFArch.WCF.DtoLibrary")]
    [System.SerializableAttribute()]
    public partial class OrderDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/WPFArch.WCF.DtoLibrary.Request.Order")]
    [System.SerializableAttribute()]
    public partial class AddOrderRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFArch.UI.BusinessLayer.OrderServiceReference.OrderDto OrderDtoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFArch.UI.BusinessLayer.OrderServiceReference.OrderDto OrderDto {
            get {
                return this.OrderDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderDtoField, value) != true)) {
                    this.OrderDtoField = value;
                    this.RaisePropertyChanged("OrderDto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddOrderResponse", Namespace="http://schemas.datacontract.org/2004/07/WPFArch.WCF.DtoLibrary.Response.Order")]
    [System.SerializableAttribute()]
    public partial class AddOrderResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/WPFArch.WCF.DtoLibrary.Request.Order")]
    [System.SerializableAttribute()]
    public partial class UpdateOrderRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFArch.UI.BusinessLayer.OrderServiceReference.OrderDto OrderDtoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFArch.UI.BusinessLayer.OrderServiceReference.OrderDto OrderDto {
            get {
                return this.OrderDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderDtoField, value) != true)) {
                    this.OrderDtoField = value;
                    this.RaisePropertyChanged("OrderDto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/WPFArch.WCF.DtoLibrary.Request.Order")]
    [System.SerializableAttribute()]
    public partial class DeleteOrderRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/WPFArch.WCF.DtoLibrary.Request.Order")]
    [System.SerializableAttribute()]
    public partial class GetOrderRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOrderResponse", Namespace="http://schemas.datacontract.org/2004/07/WPFArch.WCF.DtoLibrary.Response.Order")]
    [System.SerializableAttribute()]
    public partial class GetOrderResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFArch.UI.BusinessLayer.OrderServiceReference.OrderDto OrderDtoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFArch.UI.BusinessLayer.OrderServiceReference.OrderDto OrderDto {
            get {
                return this.OrderDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderDtoField, value) != true)) {
                    this.OrderDtoField = value;
                    this.RaisePropertyChanged("OrderDto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderServiceReference.IOrderService")]
    public interface IOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetOrderByCustomer", ReplyAction="http://tempuri.org/IOrderService/GetOrderByCustomerResponse")]
        WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderByCustomerResponse GetOrderByCustomer(WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderByCustomerReguest reguest);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOrderService/GetOrderByCustomer", ReplyAction="http://tempuri.org/IOrderService/GetOrderByCustomerResponse")]
        System.IAsyncResult BeginGetOrderByCustomer(WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderByCustomerReguest reguest, System.AsyncCallback callback, object asyncState);
        
        WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderByCustomerResponse EndGetOrderByCustomer(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/AddOrder", ReplyAction="http://tempuri.org/IOrderService/AddOrderResponse")]
        WPFArch.UI.BusinessLayer.OrderServiceReference.AddOrderResponse AddOrder(WPFArch.UI.BusinessLayer.OrderServiceReference.AddOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOrderService/AddOrder", ReplyAction="http://tempuri.org/IOrderService/AddOrderResponse")]
        System.IAsyncResult BeginAddOrder(WPFArch.UI.BusinessLayer.OrderServiceReference.AddOrderRequest request, System.AsyncCallback callback, object asyncState);
        
        WPFArch.UI.BusinessLayer.OrderServiceReference.AddOrderResponse EndAddOrder(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IOrderService/UpdateOrder")]
        void UpdateOrder(WPFArch.UI.BusinessLayer.OrderServiceReference.UpdateOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://tempuri.org/IOrderService/UpdateOrder")]
        System.IAsyncResult BeginUpdateOrder(WPFArch.UI.BusinessLayer.OrderServiceReference.UpdateOrderRequest request, System.AsyncCallback callback, object asyncState);
        
        void EndUpdateOrder(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IOrderService/DeleteOrder")]
        void DeleteOrder(WPFArch.UI.BusinessLayer.OrderServiceReference.DeleteOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://tempuri.org/IOrderService/DeleteOrder")]
        System.IAsyncResult BeginDeleteOrder(WPFArch.UI.BusinessLayer.OrderServiceReference.DeleteOrderRequest request, System.AsyncCallback callback, object asyncState);
        
        void EndDeleteOrder(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetOrder", ReplyAction="http://tempuri.org/IOrderService/GetOrderResponse")]
        WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderResponse GetOrder(WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOrderService/GetOrder", ReplyAction="http://tempuri.org/IOrderService/GetOrderResponse")]
        System.IAsyncResult BeginGetOrder(WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderRequest request, System.AsyncCallback callback, object asyncState);
        
        WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderResponse EndGetOrder(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderServiceChannel : WPFArch.UI.BusinessLayer.OrderServiceReference.IOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetOrderByCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetOrderByCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderByCustomerResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderByCustomerResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WPFArch.UI.BusinessLayer.OrderServiceReference.AddOrderResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WPFArch.UI.BusinessLayer.OrderServiceReference.AddOrderResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<WPFArch.UI.BusinessLayer.OrderServiceReference.IOrderService>, WPFArch.UI.BusinessLayer.OrderServiceReference.IOrderService {
        
        private BeginOperationDelegate onBeginGetOrderByCustomerDelegate;
        
        private EndOperationDelegate onEndGetOrderByCustomerDelegate;
        
        private System.Threading.SendOrPostCallback onGetOrderByCustomerCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddOrderDelegate;
        
        private EndOperationDelegate onEndAddOrderDelegate;
        
        private System.Threading.SendOrPostCallback onAddOrderCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateOrderDelegate;
        
        private EndOperationDelegate onEndUpdateOrderDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateOrderCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteOrderDelegate;
        
        private EndOperationDelegate onEndDeleteOrderDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteOrderCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetOrderDelegate;
        
        private EndOperationDelegate onEndGetOrderDelegate;
        
        private System.Threading.SendOrPostCallback onGetOrderCompletedDelegate;
        
        public OrderServiceClient() {
        }
        
        public OrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetOrderByCustomerCompletedEventArgs> GetOrderByCustomerCompleted;
        
        public event System.EventHandler<AddOrderCompletedEventArgs> AddOrderCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UpdateOrderCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteOrderCompleted;
        
        public event System.EventHandler<GetOrderCompletedEventArgs> GetOrderCompleted;
        
        public WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderByCustomerResponse GetOrderByCustomer(WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderByCustomerReguest reguest) {
            return base.Channel.GetOrderByCustomer(reguest);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetOrderByCustomer(WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderByCustomerReguest reguest, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetOrderByCustomer(reguest, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderByCustomerResponse EndGetOrderByCustomer(System.IAsyncResult result) {
            return base.Channel.EndGetOrderByCustomer(result);
        }
        
        private System.IAsyncResult OnBeginGetOrderByCustomer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderByCustomerReguest reguest = ((WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderByCustomerReguest)(inValues[0]));
            return this.BeginGetOrderByCustomer(reguest, callback, asyncState);
        }
        
        private object[] OnEndGetOrderByCustomer(System.IAsyncResult result) {
            WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderByCustomerResponse retVal = this.EndGetOrderByCustomer(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetOrderByCustomerCompleted(object state) {
            if ((this.GetOrderByCustomerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetOrderByCustomerCompleted(this, new GetOrderByCustomerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetOrderByCustomerAsync(WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderByCustomerReguest reguest) {
            this.GetOrderByCustomerAsync(reguest, null);
        }
        
        public void GetOrderByCustomerAsync(WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderByCustomerReguest reguest, object userState) {
            if ((this.onBeginGetOrderByCustomerDelegate == null)) {
                this.onBeginGetOrderByCustomerDelegate = new BeginOperationDelegate(this.OnBeginGetOrderByCustomer);
            }
            if ((this.onEndGetOrderByCustomerDelegate == null)) {
                this.onEndGetOrderByCustomerDelegate = new EndOperationDelegate(this.OnEndGetOrderByCustomer);
            }
            if ((this.onGetOrderByCustomerCompletedDelegate == null)) {
                this.onGetOrderByCustomerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetOrderByCustomerCompleted);
            }
            base.InvokeAsync(this.onBeginGetOrderByCustomerDelegate, new object[] {
                        reguest}, this.onEndGetOrderByCustomerDelegate, this.onGetOrderByCustomerCompletedDelegate, userState);
        }
        
        public WPFArch.UI.BusinessLayer.OrderServiceReference.AddOrderResponse AddOrder(WPFArch.UI.BusinessLayer.OrderServiceReference.AddOrderRequest request) {
            return base.Channel.AddOrder(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddOrder(WPFArch.UI.BusinessLayer.OrderServiceReference.AddOrderRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddOrder(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WPFArch.UI.BusinessLayer.OrderServiceReference.AddOrderResponse EndAddOrder(System.IAsyncResult result) {
            return base.Channel.EndAddOrder(result);
        }
        
        private System.IAsyncResult OnBeginAddOrder(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WPFArch.UI.BusinessLayer.OrderServiceReference.AddOrderRequest request = ((WPFArch.UI.BusinessLayer.OrderServiceReference.AddOrderRequest)(inValues[0]));
            return this.BeginAddOrder(request, callback, asyncState);
        }
        
        private object[] OnEndAddOrder(System.IAsyncResult result) {
            WPFArch.UI.BusinessLayer.OrderServiceReference.AddOrderResponse retVal = this.EndAddOrder(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddOrderCompleted(object state) {
            if ((this.AddOrderCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddOrderCompleted(this, new AddOrderCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddOrderAsync(WPFArch.UI.BusinessLayer.OrderServiceReference.AddOrderRequest request) {
            this.AddOrderAsync(request, null);
        }
        
        public void AddOrderAsync(WPFArch.UI.BusinessLayer.OrderServiceReference.AddOrderRequest request, object userState) {
            if ((this.onBeginAddOrderDelegate == null)) {
                this.onBeginAddOrderDelegate = new BeginOperationDelegate(this.OnBeginAddOrder);
            }
            if ((this.onEndAddOrderDelegate == null)) {
                this.onEndAddOrderDelegate = new EndOperationDelegate(this.OnEndAddOrder);
            }
            if ((this.onAddOrderCompletedDelegate == null)) {
                this.onAddOrderCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddOrderCompleted);
            }
            base.InvokeAsync(this.onBeginAddOrderDelegate, new object[] {
                        request}, this.onEndAddOrderDelegate, this.onAddOrderCompletedDelegate, userState);
        }
        
        public void UpdateOrder(WPFArch.UI.BusinessLayer.OrderServiceReference.UpdateOrderRequest request) {
            base.Channel.UpdateOrder(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginUpdateOrder(WPFArch.UI.BusinessLayer.OrderServiceReference.UpdateOrderRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateOrder(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndUpdateOrder(System.IAsyncResult result) {
            base.Channel.EndUpdateOrder(result);
        }
        
        private System.IAsyncResult OnBeginUpdateOrder(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WPFArch.UI.BusinessLayer.OrderServiceReference.UpdateOrderRequest request = ((WPFArch.UI.BusinessLayer.OrderServiceReference.UpdateOrderRequest)(inValues[0]));
            return this.BeginUpdateOrder(request, callback, asyncState);
        }
        
        private object[] OnEndUpdateOrder(System.IAsyncResult result) {
            this.EndUpdateOrder(result);
            return null;
        }
        
        private void OnUpdateOrderCompleted(object state) {
            if ((this.UpdateOrderCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateOrderCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateOrderAsync(WPFArch.UI.BusinessLayer.OrderServiceReference.UpdateOrderRequest request) {
            this.UpdateOrderAsync(request, null);
        }
        
        public void UpdateOrderAsync(WPFArch.UI.BusinessLayer.OrderServiceReference.UpdateOrderRequest request, object userState) {
            if ((this.onBeginUpdateOrderDelegate == null)) {
                this.onBeginUpdateOrderDelegate = new BeginOperationDelegate(this.OnBeginUpdateOrder);
            }
            if ((this.onEndUpdateOrderDelegate == null)) {
                this.onEndUpdateOrderDelegate = new EndOperationDelegate(this.OnEndUpdateOrder);
            }
            if ((this.onUpdateOrderCompletedDelegate == null)) {
                this.onUpdateOrderCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateOrderCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateOrderDelegate, new object[] {
                        request}, this.onEndUpdateOrderDelegate, this.onUpdateOrderCompletedDelegate, userState);
        }
        
        public void DeleteOrder(WPFArch.UI.BusinessLayer.OrderServiceReference.DeleteOrderRequest request) {
            base.Channel.DeleteOrder(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDeleteOrder(WPFArch.UI.BusinessLayer.OrderServiceReference.DeleteOrderRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteOrder(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndDeleteOrder(System.IAsyncResult result) {
            base.Channel.EndDeleteOrder(result);
        }
        
        private System.IAsyncResult OnBeginDeleteOrder(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WPFArch.UI.BusinessLayer.OrderServiceReference.DeleteOrderRequest request = ((WPFArch.UI.BusinessLayer.OrderServiceReference.DeleteOrderRequest)(inValues[0]));
            return this.BeginDeleteOrder(request, callback, asyncState);
        }
        
        private object[] OnEndDeleteOrder(System.IAsyncResult result) {
            this.EndDeleteOrder(result);
            return null;
        }
        
        private void OnDeleteOrderCompleted(object state) {
            if ((this.DeleteOrderCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteOrderCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteOrderAsync(WPFArch.UI.BusinessLayer.OrderServiceReference.DeleteOrderRequest request) {
            this.DeleteOrderAsync(request, null);
        }
        
        public void DeleteOrderAsync(WPFArch.UI.BusinessLayer.OrderServiceReference.DeleteOrderRequest request, object userState) {
            if ((this.onBeginDeleteOrderDelegate == null)) {
                this.onBeginDeleteOrderDelegate = new BeginOperationDelegate(this.OnBeginDeleteOrder);
            }
            if ((this.onEndDeleteOrderDelegate == null)) {
                this.onEndDeleteOrderDelegate = new EndOperationDelegate(this.OnEndDeleteOrder);
            }
            if ((this.onDeleteOrderCompletedDelegate == null)) {
                this.onDeleteOrderCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteOrderCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteOrderDelegate, new object[] {
                        request}, this.onEndDeleteOrderDelegate, this.onDeleteOrderCompletedDelegate, userState);
        }
        
        public WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderResponse GetOrder(WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderRequest request) {
            return base.Channel.GetOrder(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetOrder(WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetOrder(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderResponse EndGetOrder(System.IAsyncResult result) {
            return base.Channel.EndGetOrder(result);
        }
        
        private System.IAsyncResult OnBeginGetOrder(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderRequest request = ((WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderRequest)(inValues[0]));
            return this.BeginGetOrder(request, callback, asyncState);
        }
        
        private object[] OnEndGetOrder(System.IAsyncResult result) {
            WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderResponse retVal = this.EndGetOrder(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetOrderCompleted(object state) {
            if ((this.GetOrderCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetOrderCompleted(this, new GetOrderCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetOrderAsync(WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderRequest request) {
            this.GetOrderAsync(request, null);
        }
        
        public void GetOrderAsync(WPFArch.UI.BusinessLayer.OrderServiceReference.GetOrderRequest request, object userState) {
            if ((this.onBeginGetOrderDelegate == null)) {
                this.onBeginGetOrderDelegate = new BeginOperationDelegate(this.OnBeginGetOrder);
            }
            if ((this.onEndGetOrderDelegate == null)) {
                this.onEndGetOrderDelegate = new EndOperationDelegate(this.OnEndGetOrder);
            }
            if ((this.onGetOrderCompletedDelegate == null)) {
                this.onGetOrderCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetOrderCompleted);
            }
            base.InvokeAsync(this.onBeginGetOrderDelegate, new object[] {
                        request}, this.onEndGetOrderDelegate, this.onGetOrderCompletedDelegate, userState);
        }
    }
}
