//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFArch.UI.BusinessLayer.CustomerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCustomersResponse", Namespace="http://schemas.datacontract.org/2004/07/WPFArch.WCF.DtoLibrary.Response.Customer")]
    [System.SerializableAttribute()]
    public partial class GetCustomersResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WPFArch.UI.BusinessLayer.CustomerServiceReference.CustomerDto> CustomersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WPFArch.UI.BusinessLayer.CustomerServiceReference.CustomerDto> Customers {
            get {
                return this.CustomersField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomersField, value) != true)) {
                    this.CustomersField = value;
                    this.RaisePropertyChanged("Customers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDto", Namespace="http://schemas.datacontract.org/2004/07/WPFArch.WCF.DtoLibrary")]
    [System.SerializableAttribute()]
    public partial class CustomerDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddCustomerRequest", Namespace="http://schemas.datacontract.org/2004/07/WPFArch.WCF.DtoLibrary.Request.Customer")]
    [System.SerializableAttribute()]
    public partial class AddCustomerRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFArch.UI.BusinessLayer.CustomerServiceReference.CustomerDto CustomerDtoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFArch.UI.BusinessLayer.CustomerServiceReference.CustomerDto CustomerDto {
            get {
                return this.CustomerDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerDtoField, value) != true)) {
                    this.CustomerDtoField = value;
                    this.RaisePropertyChanged("CustomerDto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddCustomerResponse", Namespace="http://schemas.datacontract.org/2004/07/WPFArch.WCF.DtoLibrary.Response.Customer")]
    [System.SerializableAttribute()]
    public partial class AddCustomerResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateCustomerRequest", Namespace="http://schemas.datacontract.org/2004/07/WPFArch.WCF.DtoLibrary.Request.Customer")]
    [System.SerializableAttribute()]
    public partial class UpdateCustomerRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFArch.UI.BusinessLayer.CustomerServiceReference.CustomerDto CustomerDtoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFArch.UI.BusinessLayer.CustomerServiceReference.CustomerDto CustomerDto {
            get {
                return this.CustomerDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerDtoField, value) != true)) {
                    this.CustomerDtoField = value;
                    this.RaisePropertyChanged("CustomerDto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteCustomerRequest", Namespace="http://schemas.datacontract.org/2004/07/WPFArch.WCF.DtoLibrary.Request.Customer")]
    [System.SerializableAttribute()]
    public partial class DeleteCustomerRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerServiceReference.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomers", ReplyAction="http://tempuri.org/ICustomerService/GetCustomersResponse")]
        WPFArch.UI.BusinessLayer.CustomerServiceReference.GetCustomersResponse GetCustomers();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICustomerService/GetCustomers", ReplyAction="http://tempuri.org/ICustomerService/GetCustomersResponse")]
        System.IAsyncResult BeginGetCustomers(System.AsyncCallback callback, object asyncState);
        
        WPFArch.UI.BusinessLayer.CustomerServiceReference.GetCustomersResponse EndGetCustomers(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/AddCustomer", ReplyAction="http://tempuri.org/ICustomerService/AddCustomerResponse")]
        WPFArch.UI.BusinessLayer.CustomerServiceReference.AddCustomerResponse AddCustomer(WPFArch.UI.BusinessLayer.CustomerServiceReference.AddCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICustomerService/AddCustomer", ReplyAction="http://tempuri.org/ICustomerService/AddCustomerResponse")]
        System.IAsyncResult BeginAddCustomer(WPFArch.UI.BusinessLayer.CustomerServiceReference.AddCustomerRequest request, System.AsyncCallback callback, object asyncState);
        
        WPFArch.UI.BusinessLayer.CustomerServiceReference.AddCustomerResponse EndAddCustomer(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICustomerService/UpdateCustomer")]
        void UpdateCustomer(WPFArch.UI.BusinessLayer.CustomerServiceReference.UpdateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://tempuri.org/ICustomerService/UpdateCustomer")]
        System.IAsyncResult BeginUpdateCustomer(WPFArch.UI.BusinessLayer.CustomerServiceReference.UpdateCustomerRequest request, System.AsyncCallback callback, object asyncState);
        
        void EndUpdateCustomer(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICustomerService/DeleteCustomer")]
        void DeleteCustomer(WPFArch.UI.BusinessLayer.CustomerServiceReference.DeleteCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://tempuri.org/ICustomerService/DeleteCustomer")]
        System.IAsyncResult BeginDeleteCustomer(WPFArch.UI.BusinessLayer.CustomerServiceReference.DeleteCustomerRequest request, System.AsyncCallback callback, object asyncState);
        
        void EndDeleteCustomer(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : WPFArch.UI.BusinessLayer.CustomerServiceReference.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WPFArch.UI.BusinessLayer.CustomerServiceReference.GetCustomersResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WPFArch.UI.BusinessLayer.CustomerServiceReference.GetCustomersResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WPFArch.UI.BusinessLayer.CustomerServiceReference.AddCustomerResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WPFArch.UI.BusinessLayer.CustomerServiceReference.AddCustomerResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<WPFArch.UI.BusinessLayer.CustomerServiceReference.ICustomerService>, WPFArch.UI.BusinessLayer.CustomerServiceReference.ICustomerService {
        
        private BeginOperationDelegate onBeginGetCustomersDelegate;
        
        private EndOperationDelegate onEndGetCustomersDelegate;
        
        private System.Threading.SendOrPostCallback onGetCustomersCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddCustomerDelegate;
        
        private EndOperationDelegate onEndAddCustomerDelegate;
        
        private System.Threading.SendOrPostCallback onAddCustomerCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateCustomerDelegate;
        
        private EndOperationDelegate onEndUpdateCustomerDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateCustomerCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteCustomerDelegate;
        
        private EndOperationDelegate onEndDeleteCustomerDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteCustomerCompletedDelegate;
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetCustomersCompletedEventArgs> GetCustomersCompleted;
        
        public event System.EventHandler<AddCustomerCompletedEventArgs> AddCustomerCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UpdateCustomerCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteCustomerCompleted;
        
        public WPFArch.UI.BusinessLayer.CustomerServiceReference.GetCustomersResponse GetCustomers() {
            return base.Channel.GetCustomers();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetCustomers(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCustomers(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WPFArch.UI.BusinessLayer.CustomerServiceReference.GetCustomersResponse EndGetCustomers(System.IAsyncResult result) {
            return base.Channel.EndGetCustomers(result);
        }
        
        private System.IAsyncResult OnBeginGetCustomers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetCustomers(callback, asyncState);
        }
        
        private object[] OnEndGetCustomers(System.IAsyncResult result) {
            WPFArch.UI.BusinessLayer.CustomerServiceReference.GetCustomersResponse retVal = this.EndGetCustomers(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCustomersCompleted(object state) {
            if ((this.GetCustomersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCustomersCompleted(this, new GetCustomersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCustomersAsync() {
            this.GetCustomersAsync(null);
        }
        
        public void GetCustomersAsync(object userState) {
            if ((this.onBeginGetCustomersDelegate == null)) {
                this.onBeginGetCustomersDelegate = new BeginOperationDelegate(this.OnBeginGetCustomers);
            }
            if ((this.onEndGetCustomersDelegate == null)) {
                this.onEndGetCustomersDelegate = new EndOperationDelegate(this.OnEndGetCustomers);
            }
            if ((this.onGetCustomersCompletedDelegate == null)) {
                this.onGetCustomersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCustomersCompleted);
            }
            base.InvokeAsync(this.onBeginGetCustomersDelegate, null, this.onEndGetCustomersDelegate, this.onGetCustomersCompletedDelegate, userState);
        }
        
        public WPFArch.UI.BusinessLayer.CustomerServiceReference.AddCustomerResponse AddCustomer(WPFArch.UI.BusinessLayer.CustomerServiceReference.AddCustomerRequest request) {
            return base.Channel.AddCustomer(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddCustomer(WPFArch.UI.BusinessLayer.CustomerServiceReference.AddCustomerRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddCustomer(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WPFArch.UI.BusinessLayer.CustomerServiceReference.AddCustomerResponse EndAddCustomer(System.IAsyncResult result) {
            return base.Channel.EndAddCustomer(result);
        }
        
        private System.IAsyncResult OnBeginAddCustomer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WPFArch.UI.BusinessLayer.CustomerServiceReference.AddCustomerRequest request = ((WPFArch.UI.BusinessLayer.CustomerServiceReference.AddCustomerRequest)(inValues[0]));
            return this.BeginAddCustomer(request, callback, asyncState);
        }
        
        private object[] OnEndAddCustomer(System.IAsyncResult result) {
            WPFArch.UI.BusinessLayer.CustomerServiceReference.AddCustomerResponse retVal = this.EndAddCustomer(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddCustomerCompleted(object state) {
            if ((this.AddCustomerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddCustomerCompleted(this, new AddCustomerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddCustomerAsync(WPFArch.UI.BusinessLayer.CustomerServiceReference.AddCustomerRequest request) {
            this.AddCustomerAsync(request, null);
        }
        
        public void AddCustomerAsync(WPFArch.UI.BusinessLayer.CustomerServiceReference.AddCustomerRequest request, object userState) {
            if ((this.onBeginAddCustomerDelegate == null)) {
                this.onBeginAddCustomerDelegate = new BeginOperationDelegate(this.OnBeginAddCustomer);
            }
            if ((this.onEndAddCustomerDelegate == null)) {
                this.onEndAddCustomerDelegate = new EndOperationDelegate(this.OnEndAddCustomer);
            }
            if ((this.onAddCustomerCompletedDelegate == null)) {
                this.onAddCustomerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddCustomerCompleted);
            }
            base.InvokeAsync(this.onBeginAddCustomerDelegate, new object[] {
                        request}, this.onEndAddCustomerDelegate, this.onAddCustomerCompletedDelegate, userState);
        }
        
        public void UpdateCustomer(WPFArch.UI.BusinessLayer.CustomerServiceReference.UpdateCustomerRequest request) {
            base.Channel.UpdateCustomer(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginUpdateCustomer(WPFArch.UI.BusinessLayer.CustomerServiceReference.UpdateCustomerRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateCustomer(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndUpdateCustomer(System.IAsyncResult result) {
            base.Channel.EndUpdateCustomer(result);
        }
        
        private System.IAsyncResult OnBeginUpdateCustomer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WPFArch.UI.BusinessLayer.CustomerServiceReference.UpdateCustomerRequest request = ((WPFArch.UI.BusinessLayer.CustomerServiceReference.UpdateCustomerRequest)(inValues[0]));
            return this.BeginUpdateCustomer(request, callback, asyncState);
        }
        
        private object[] OnEndUpdateCustomer(System.IAsyncResult result) {
            this.EndUpdateCustomer(result);
            return null;
        }
        
        private void OnUpdateCustomerCompleted(object state) {
            if ((this.UpdateCustomerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateCustomerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateCustomerAsync(WPFArch.UI.BusinessLayer.CustomerServiceReference.UpdateCustomerRequest request) {
            this.UpdateCustomerAsync(request, null);
        }
        
        public void UpdateCustomerAsync(WPFArch.UI.BusinessLayer.CustomerServiceReference.UpdateCustomerRequest request, object userState) {
            if ((this.onBeginUpdateCustomerDelegate == null)) {
                this.onBeginUpdateCustomerDelegate = new BeginOperationDelegate(this.OnBeginUpdateCustomer);
            }
            if ((this.onEndUpdateCustomerDelegate == null)) {
                this.onEndUpdateCustomerDelegate = new EndOperationDelegate(this.OnEndUpdateCustomer);
            }
            if ((this.onUpdateCustomerCompletedDelegate == null)) {
                this.onUpdateCustomerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateCustomerCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateCustomerDelegate, new object[] {
                        request}, this.onEndUpdateCustomerDelegate, this.onUpdateCustomerCompletedDelegate, userState);
        }
        
        public void DeleteCustomer(WPFArch.UI.BusinessLayer.CustomerServiceReference.DeleteCustomerRequest request) {
            base.Channel.DeleteCustomer(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDeleteCustomer(WPFArch.UI.BusinessLayer.CustomerServiceReference.DeleteCustomerRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteCustomer(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndDeleteCustomer(System.IAsyncResult result) {
            base.Channel.EndDeleteCustomer(result);
        }
        
        private System.IAsyncResult OnBeginDeleteCustomer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WPFArch.UI.BusinessLayer.CustomerServiceReference.DeleteCustomerRequest request = ((WPFArch.UI.BusinessLayer.CustomerServiceReference.DeleteCustomerRequest)(inValues[0]));
            return this.BeginDeleteCustomer(request, callback, asyncState);
        }
        
        private object[] OnEndDeleteCustomer(System.IAsyncResult result) {
            this.EndDeleteCustomer(result);
            return null;
        }
        
        private void OnDeleteCustomerCompleted(object state) {
            if ((this.DeleteCustomerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteCustomerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteCustomerAsync(WPFArch.UI.BusinessLayer.CustomerServiceReference.DeleteCustomerRequest request) {
            this.DeleteCustomerAsync(request, null);
        }
        
        public void DeleteCustomerAsync(WPFArch.UI.BusinessLayer.CustomerServiceReference.DeleteCustomerRequest request, object userState) {
            if ((this.onBeginDeleteCustomerDelegate == null)) {
                this.onBeginDeleteCustomerDelegate = new BeginOperationDelegate(this.OnBeginDeleteCustomer);
            }
            if ((this.onEndDeleteCustomerDelegate == null)) {
                this.onEndDeleteCustomerDelegate = new EndOperationDelegate(this.OnEndDeleteCustomer);
            }
            if ((this.onDeleteCustomerCompletedDelegate == null)) {
                this.onDeleteCustomerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteCustomerCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteCustomerDelegate, new object[] {
                        request}, this.onEndDeleteCustomerDelegate, this.onDeleteCustomerCompletedDelegate, userState);
        }
    }
}
